### ISSUE TITLE
Adding CITATION.cff for convenient citation

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#19]
It would be best to add a [CITATION.cff](https://citation-file-format.github.io/) (maybe also a DOI) in the repo, this will facillitate a precise citation.

Example
```yml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/1234-5678-9101-1121
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2021-08-11
```
